version: '3.9'

networks:
  default:
    name: 'tfa'

services:
  postgres:
    container_name: 'tfa-postgres'
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_DB: Malove.TFA.Forum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - tfa-postgres:/var/lib/postgresql/data

  loki:
    container_name: 'tfa-loki'
    image: 'grafana/loki'
    ports:
      - '3100:3100'
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
    command: >
      --config.file=/etc/loki/local-config.yml
      -validation.allow-structured-metadata=false
    
  prometheus:
    container_name: 'tfa-prom'
    image: 'prom/prometheus'
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - tfa-prom:/prometheus

  grafana:
    container_name: 'tfa-grafana'
    image: 'grafana/grafana'
    restart: unless-stopped
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - tfa-grafana:/var/lib/grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    
  jaeger:
    container_name: 'tfa-jaeger'
    image: 'jaegertracing/all-in-one:1.9'
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '9411:9411'  
  
volumes:
  tfa-postgres:
  tfa-loki:
  tfa-prom:
  tfa-grafana: